version: '3.8'

services:
  app:
    image: louislam/uptime-kuma:1.22.1-alpine
    container_name: uptime-kuma-app
    #ports:
    #  - 3001:3001
    volumes:
      - $(pwd)/lib_upkdata:/app/data
    networks:
      - uptimekuma-net
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', 'extra/healthcheck.js']
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

networks:
  uptimekuma-net:
    name: uptimekuma-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
