version: '3.9'

services:
  app:
    image: louislam/uptime-kuma:1.22.1-alpine
    volumes:
      - $(pwd)/lib_upkdata:/app/data
    networks:
      - uptimekuma-net
    healthcheck:
      test: [ 'CMD', 'node', 'extra/healthcheck.js' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
      resources:
        limits:
          cpus: '1.5'
          memory: 256M

networks:
  uptimekuma-net:
    name: uptimekuma-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
